"""Provider-neutral storyboard image generation backends."""

from __future__ import annotations

import base64
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import time
from typing import Any, Protocol
from urllib import error, request
import zlib


DEFAULT_OPENAI_IMAGE_MODEL = "gpt-image-2"
DEFAULT_OPENAI_IMAGE_SIZE = "1536x1024"
DEFAULT_OPENAI_IMAGE_QUALITY = "medium"
DEFAULT_OPENAI_IMAGE_FORMAT = "png"


class ProviderError(RuntimeError):
    """Raised when a provider cannot produce an image for a panel job."""


@dataclass(frozen=True)
class GenerationResult:
    provider: str
    model: str
    image_bytes: bytes
    request_metadata: dict[str, Any]
    provider_job_id: str | None = None
    output_format: str = "png"
    seed: int | None = None
    cost_estimate: str | None = None
    notes: str = ""


class ImageProvider(Protocol):
    name: str
    model: str

    def generate(self, job: dict[str, Any]) -> GenerationResult:
        """Generate one storyboard panel image for a pending job."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def png_chunk(kind: bytes, data: bytes) -> bytes:
    return (
        len(data).to_bytes(4, "big")
        + kind
        + data
        + zlib.crc32(kind + data).to_bytes(4, "big")
    )


def fake_png(label: str) -> bytes:
    text = f"scriptboard\x00{label}".encode("utf-8", errors="replace")
    raw_pixel = b"\x00\x25\x4a\x70"
    return b"".join(
        [
            b"\x89PNG\r\n\x1a\n",
            png_chunk(b"IHDR", b"\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00"),
            png_chunk(b"tEXt", text),
            png_chunk(b"IDAT", zlib.compress(raw_pixel)),
            png_chunk(b"IEND", b""),
        ]
    )


class FakeImageProvider:
    """Deterministic test provider that writes tiny PNG fixtures."""

    name = "fake"
    model = "fake-image-provider"

    def __init__(self, fail_job_ids: set[str] | None = None) -> None:
        self.fail_job_ids = fail_job_ids or set()

    def generate(self, job: dict[str, Any]) -> GenerationResult:
        job_id = str(job.get("id") or "")
        if job_id in self.fail_job_ids:
            raise ProviderError(f"Fake provider failure for {job_id}")
        prompt_hash = str(job.get("prompt_hash") or "")
        return GenerationResult(
            provider=self.name,
            model=self.model,
            image_bytes=fake_png(f"{job_id}:{prompt_hash}"),
            request_metadata={
                "provider": self.name,
                "job_id": job_id,
                "prompt_hash": prompt_hash,
            },
            provider_job_id=f"fake-{job_id}",
            notes="Generated by ScriptBoard fake provider for deterministic tests.",
        )


class OpenAIImageProvider:
    """OpenAI Image API provider for prompt-to-local-image generation."""

    name = "openai"

    def __init__(
        self,
        *,
        api_key: str | None = None,
        model: str = DEFAULT_OPENAI_IMAGE_MODEL,
        size: str = DEFAULT_OPENAI_IMAGE_SIZE,
        quality: str = DEFAULT_OPENAI_IMAGE_QUALITY,
        output_format: str = DEFAULT_OPENAI_IMAGE_FORMAT,
        timeout_s: int = 180,
    ) -> None:
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model
        self.size = size
        self.quality = quality
        self.output_format = output_format
        self.timeout_s = timeout_s

    def request_payload(self, job: dict[str, Any]) -> dict[str, Any]:
        return {
            "model": self.model,
            "prompt": str(job.get("prompt") or ""),
            "n": 1,
            "size": self.size,
            "quality": self.quality,
            "output_format": self.output_format,
        }

    def generate(self, job: dict[str, Any]) -> GenerationResult:
        if not self.api_key:
            raise ProviderError("OPENAI_API_KEY is required for provider 'openai'")
        payload = self.request_payload(job)
        request_metadata = {key: value for key, value in payload.items() if key != "prompt"}
        request_metadata["prompt_hash"] = str(job.get("prompt_hash") or sha256_bytes(payload["prompt"].encode("utf-8")))
        req = request.Request(
            "https://api.openai.com/v1/images/generations",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=self.timeout_s) as response:
                body = json.loads(response.read().decode("utf-8"))
                request_id = response.headers.get("x-request-id")
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(f"OpenAI Image API failed with HTTP {exc.code}: {detail}") from exc
        except error.URLError as exc:
            raise ProviderError(f"OpenAI Image API request failed: {exc}") from exc
        try:
            encoded = body["data"][0]["b64_json"]
        except (KeyError, IndexError, TypeError) as exc:
            raise ProviderError("OpenAI Image API response did not include data[0].b64_json") from exc
        return GenerationResult(
            provider=self.name,
            model=self.model,
            image_bytes=base64.b64decode(encoded),
            request_metadata=request_metadata,
            provider_job_id=request_id,
            output_format=self.output_format,
            notes="Generated by OpenAI Image API; image bytes decoded from data[0].b64_json.",
        )


def make_provider(
    name: str,
    *,
    model: str | None = None,
    size: str = DEFAULT_OPENAI_IMAGE_SIZE,
    quality: str = DEFAULT_OPENAI_IMAGE_QUALITY,
    output_format: str = DEFAULT_OPENAI_IMAGE_FORMAT,
) -> ImageProvider:
    if name == "fake":
        return FakeImageProvider()
    if name == "openai":
        return OpenAIImageProvider(
            model=model or DEFAULT_OPENAI_IMAGE_MODEL,
            size=size,
            quality=quality,
            output_format=output_format,
        )
    raise ValueError(f"Unknown image provider: {name}")


def load_ledger(ledger_path: Path) -> dict[str, Any]:
    return json.loads(ledger_path.read_text(encoding="utf-8"))


def save_ledger(ledger_path: Path, raw: dict[str, Any]) -> None:
    refresh_summary(raw)
    raw["generated_at"] = utc_now()
    ledger_path.write_text(json.dumps(raw, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def refresh_summary(raw: dict[str, Any]) -> None:
    jobs = list(raw.get("jobs", []))
    done = sum(1 for job in jobs if job.get("status") == "done" and Path(str(job.get("image_path") or "")).exists())
    failed = sum(1 for job in jobs if job.get("status") == "failed")
    raw["summary"] = {
        "total": len(jobs),
        "pending": len(jobs) - done - failed,
        "done": done,
        "failed": failed,
    }


def job_image_path(job: dict[str, Any]) -> Path:
    return Path(str(job.get("image_path") or ""))


def job_selection_blocker(job: dict[str, Any], *, retry_failed: bool = False) -> str:
    image_path = job_image_path(job)
    if job.get("status") == "done" and image_path.exists():
        return "job is already done and its image file exists"
    if job.get("status") == "failed" and not retry_failed:
        return "job is failed; pass --retry-failed to select it"
    if image_path.exists():
        return "image file already exists"
    return ""


def job_preview(job: dict[str, Any]) -> dict[str, Any]:
    image_path = job_image_path(job)
    provider = job.get("provider") or {}
    return {
        "id": job.get("id"),
        "status": job.get("status"),
        "scene_id": job.get("scene_id"),
        "panel_index": job.get("panel_index"),
        "panel_label": job.get("panel_label"),
        "prompt_hash": job.get("prompt_hash"),
        "image_path": str(image_path),
        "image_exists": image_path.exists(),
        "provider": provider.get("provider"),
        "provider_status": provider.get("status"),
    }


def selected_jobs(
    raw: dict[str, Any],
    *,
    limit: int,
    retry_failed: bool = False,
    job_id: str | None = None,
) -> list[dict[str, Any]]:
    if limit < 1:
        raise ValueError("limit must be at least 1")
    if job_id:
        for job in raw.get("jobs", []):
            if job.get("id") != job_id:
                continue
            blocker = job_selection_blocker(job, retry_failed=retry_failed)
            if blocker:
                raise ProviderError(f"Job {job_id} is not selectable: {blocker}")
            return [job]
        raise ProviderError(f"Job id not found: {job_id}")

    jobs = []
    for job in raw.get("jobs", []):
        if job_selection_blocker(job, retry_failed=retry_failed):
            continue
        jobs.append(job)
        if len(jobs) >= limit:
            break
    return jobs


def generation_plan(
    raw: dict[str, Any],
    *,
    limit: int,
    retry_failed: bool = False,
    job_id: str | None = None,
) -> dict[str, Any]:
    refresh_summary(raw)
    selected = selected_jobs(raw, limit=limit, retry_failed=retry_failed, job_id=job_id)
    return {
        "summary": raw.get("summary", {}),
        "selection": {
            "limit": limit,
            "retry_failed": retry_failed,
            "job_id": job_id,
            "selected": len(selected),
        },
        "jobs": [job_preview(job) for job in selected],
    }


def provider_metadata(
    *,
    provider: ImageProvider,
    result: GenerationResult | None,
    status: str,
    started_at: str,
    completed_at: str | None = None,
    checksum: str | None = None,
    output_path: str | None = None,
    error_message: str | None = None,
) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "provider": provider.name,
        "model": provider.model,
        "status": status,
        "started_at": started_at,
        "completed_at": completed_at,
    }
    if result:
        metadata.update(
            {
                "provider_job_id": result.provider_job_id,
                "request_metadata": result.request_metadata,
                "output_format": result.output_format,
                "seed": result.seed,
                "cost_estimate": result.cost_estimate,
                "notes": result.notes,
            }
        )
    if checksum:
        metadata["checksum_sha256"] = checksum
    if output_path:
        metadata["output_path"] = output_path
    if error_message:
        metadata["error"] = error_message
    return metadata


def run_provider_generation(
    ledger_path: Path,
    provider: ImageProvider,
    *,
    limit: int,
    retry_failed: bool = False,
    stop_on_error: bool = False,
    job_id: str | None = None,
) -> dict[str, int]:
    raw = load_ledger(ledger_path)
    selected = selected_jobs(raw, limit=limit, retry_failed=retry_failed, job_id=job_id)
    counts = {"selected": len(selected), "completed": 0, "failed": 0}
    for job in selected:
        started_at = utc_now()
        job["status"] = "running"
        job["updated_at"] = started_at
        job["provider"] = provider_metadata(provider=provider, result=None, status="running", started_at=started_at)
        save_ledger(ledger_path, raw)
        try:
            result = provider.generate(job)
            output = Path(str(job["image_path"]))
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(result.image_bytes)
            digest = sha256_bytes(result.image_bytes)
            completed_at = utc_now()
            job["status"] = "done"
            job["output_path"] = str(output)
            job["updated_at"] = completed_at
            job["notes"] = result.notes
            job["provider"] = provider_metadata(
                provider=provider,
                result=result,
                status="done",
                started_at=started_at,
                completed_at=completed_at,
                checksum=digest,
                output_path=str(output),
            )
            counts["completed"] += 1
        except Exception as exc:
            completed_at = utc_now()
            message = str(exc)
            job["status"] = "failed"
            job["updated_at"] = completed_at
            job["notes"] = message
            job["provider"] = provider_metadata(
                provider=provider,
                result=None,
                status="failed",
                started_at=started_at,
                completed_at=completed_at,
                error_message=message,
            )
            counts["failed"] += 1
            save_ledger(ledger_path, raw)
            if stop_on_error:
                raise ProviderError(message) from exc
        save_ledger(ledger_path, raw)
        time.sleep(0)
    return counts
